#' HELPER: Create analysis R script for LTM report template
#'
#' @description
#' A helper function, intended to be called from within [flfishltm::create_ltm_report()]
#' 
#' @param catch_data (string) name of a csv file containing catch data. 
#'   Data should be in format generated by 'Standard Fish Query' and stored in 
#'   the /data directory of the ltm report template.
#' @param age_data [FUTURE FEATURE](string) name of a csv file containing age data
#'
#' @return (string) containing r script text
#' @export
#'
#' @examples
#' 
#' \dontrun{
#' create_ltm_analysis_template()
#' }
#' 
#' 
create_ltm_analysis_template <- function(catch_data = "qryFish_standard.csv",
                                         age_data = NULL,
                                         habitat_data = NULL) {
paste("
# Load Packages ------------------------------------------------------------
    
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(flfishltm))
    
    
theme_angle_text <- function() {
  theme(text = element_text(family = 'sans'),
          axis.text.x = element_text(angle = 45,
                                       hjust = 1,
                                       vjust = 1,
                                       size = 9,
                                       margin=margin(0,0,0,0))) 
    }
# Reference dataset ------------------------------------------------------------

catch <- \"",catch_data,"\"

age <- NULL

habitat <- NULL

# Process data -----------------------------------------------------------------

if(stringr::str_sub(catch, -4) != \".csv\") {
catch <- paste(catch, \".csv\", sep=\"\")
}

catch <- 
  paste(\"data/\",catch,sep=\"\") %>%
  read.csv() %>%
  data.frame()

lake <- catch %>% distinct(WaterBody) %>% pull(WaterBody) %>% .[1]

dsum <- ltm.data.summary(lake, catch)

catch <-
  catch %>%
  mutate(Date = as.Date(Date, \"%m/%d/%Y\")) %>%
  mutate(year = as.numeric(format(Date, \"%Y\")))

## Calculate variables ---------------------------------------------------------

target <- 
  catch %>% 
  distinct(Target) %>% 
  pull(Target) 

if(length(target) > 1) stop(\"Multiple targets included in dataset\")


sample_date <- 
  catch %>%
  group_by(year) %>%
  summarise(startD = min(Date),
            endD = max(Date)) %>%
  filter(year == max(year))

RelWt <-
  dsum$RawData %>%
  #filter(TL_CM_Group >= 30) %>%
  mutate(relWt = flfishltm::Wr(., \"TotalLength\", \"TotalWeight\", a = -5.47045, b = 3.24105),
         year = as.numeric(format(as.Date(Date, \"%m/%d/%Y\"), \"%Y\")))

RelWt30 <-
  dsum$RawData %>%
  filter(TL_CM_Group >= 30) %>%
  mutate(relWt = flfishltm::Wr(., \"TotalLength\", \"TotalWeight\", a = -5.47045, b = 3.24105),
         year = as.numeric(format(as.Date(Date, \"%m/%d/%Y\"), \"%Y\")))

RelWt_sum <- 
  tibble(year = min(RelWt$year):max(RelWt$year)) %>%
  left_join(RelWt %>%
              group_by(year) %>%
              summarise(Wr = mean(relWt, na.rm = TRUE),
                        Wrse = sd(relWt, na.rm = TRUE)/sqrt(n())), by = \"year\")

wt_chk <- 
  ggplot(data = RelWt %>% filter(year == max(year)), aes(x = TotalLength, y = TotalWeight)) +
  geom_point()

# plotly::ggplotly(wt_chk)

fhc_sum <- 
  RelWt %>%
  filter(year > 2020) %>%  # FHC codes not implemented until 2021
  group_by(year, FishHealthCode) %>% 
  count() %>% 
  ungroup() %>% 
  group_by(year) %>% 
  mutate(pct = n/sum(n)*100) %>% 
  ungroup()

fhc_nocode <- 
  fhc_sum %>%
  filter(year == max(fhc_sum$year), FishHealthCode == \"\") %>% 
  pull(pct) %>%
  round(2)    

# RSD/PSD ----------------------------------------------------------------------

rsd_cpue <- 
  cpue.plot(dsum,
            speciesList = \"LMB\",
            species_size_strata = list(
                      LMB = list(Substock = c(0,29),
                                 Quality = c(30,37),
                                 Pref = c(40,100))),
                    print = FALSE,
                    figure_filename = paste(lake, \"_\", rsd, sep = \"\"),
                    fig_scale = 6)

stockdensity <- 
  rsd_cpue %>% 
  mutate(stockcat = ifelse(sizeStrata == \"Substock\", \"Substock\", \"StockPlus\"), 
         prefCat = ifelse(sizeStrata == \"Pref\", \"Pref\", \"Subpref\")) %>%
  group_by(Year,stockcat) %>% 
  summarize(meanCPUE = sum(mean_CPUE)) %>%
  ungroup() %>% 
  group_by(Year) %>% 
  mutate(stockdensity = meanCPUE/sum(meanCPUE)) %>% 
  filter(stockcat == \"StockPlus\") %>% 
  ungroup()

prefdensity <- rsd_cpue %>% 
  mutate(stockcat = ifelse(sizeStrata == \"Substock\", \"Substock\", \"StockPlus\"), prefCat = ifelse(sizeStrata == \"Pref\", \"Pref\", \"Subpref\")) %>%
  group_by(Year,stockcat = prefCat) %>% summarize(meanCPUE = sum(mean_CPUE)) %>% ungroup() %>% group_by(Year) %>% mutate(stockdensity = meanCPUE/sum(meanCPUE)) %>% 
  filter(stockcat == \"Pref\") %>% ungroup()

StockDensity <- 
  tibble(Year = c(min(stockdensity$Year):max(stockdensity$Year))) %>% 
  full_join(rbind(stockdensity, prefdensity) %>%
              distinct(stockcat), by = character()) %>% 
  left_join(rbind(stockdensity, prefdensity))

PSD_plot <- ggplot(data = StockDensity, 
                   aes(x = Year, y = stockdensity, color = stockcat)) + 
  geom_point() +
  geom_line() +
  xlab(\"Year\") + ylab(\"Proportional Stock Density (%)\") + 
  scale_color_discrete(labels = c(\"RSD-P\", \"PSD\")) +
  scale_x_continuous(breaks = scales::breaks_width(1)) +
  theme_ltm() +
  theme_angle_text()


# save objects for inserting into report text ----------------------------------

start_date <- pull(sample_date, startD)
end_date <- pull(sample_date, endD)

text_start <- format(start_date, \"%B %d\")
text_end <- format(end_date, \"%B %d, %Y\")
n_tran <- dsum$Year_Sites[nrow(dsum$Year_Sites), 2]
cpue <- dsum$CPUE_number[nrow(dsum$CPUE_number), \"Largemouth Bass\"] %>% round(., 2)
cpue_se <- dsum$CPUE_number_SE[nrow(dsum$CPUE_number_SE), \"Largemouth Bass\"] %>% round(., 2)
n_tot <- catch %>% filter(year == max(catch$year)) %>% summarise(total = sum(Count)) %>% pull(total)

tg <- stringr::str_pad(target, 15, 'right')
wb <- stringr::str_pad(lake, 15, 'right')
st <- stringr::str_pad(paste(start_date), 15, 'right')
ed <- stringr::str_pad(paste(end_date), 15, 'right')

rsdp <- 
  StockDensity %>% 
  filter(Year == max(StockDensity$Year), stockcat == \"StockPlus\") %>%
  pull(stockdensity)

psd <- 
  StockDensity %>%
  filter(Year == max(StockDensity$Year), stockcat == \"Pref\") %>% 
  pull(stockdensity)

out <- 
  tibble(cm = c(0:70)) %>% 
  left_join(catch %>% 
              filter(year == 2022) %>%
              group_by(TL_CM_Group) %>% 
              summarise(total = sum(Count)) %>% 
              select(cm = TL_CM_Group, total), by = \"cm\") %>% 
  mutate(total = replace_na(total, 0))

yr <- lubridate::year(end_date)

write.csv(out, 
          file = paste(\"tables/\", stringr::str_replace(lake, \" \", \"_\"),
                       \"_\", target, \"_\", yr, \"_SizeStructure.csv\", sep=\"\"))   
      
    
    ",

sep = ""
)
}

